# Generated by Django 2.2.4 on 2019-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, default='padrao.png', upload_to=''),
        ),
    ]
