# Generated by Django 2.2.4 on 2019-08-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumb',
        ),
    ]
