# Generated by Django 2.2.4 on 2019-08-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, default='padrao.jpg', upload_to=''),
        ),
    ]
