# Generated by Django 2.2.4 on 2019-09-03 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
