# Generated by Django 2.2.4 on 2019-10-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20191008_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(upload_to=''),
        ),
    ]
