# Generated by Django 2.2.4 on 2019-10-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20191008_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumb',
        ),
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='padrao.jpg', height_field='height_field', upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='post',
            name='widht_field',
            field=models.IntegerField(default=0),
        ),
    ]
