# Generated by Django 2.2.4 on 2019-10-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20191009_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='widht_field',
            new_name='width_field',
        ),
    ]
