# Generated by Django 2.2.4 on 2019-10-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20191009_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='thumb',
        ),
    ]
