# Generated by Django 2.2.4 on 2019-10-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20191009_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clip',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
